### ISSUE TITLE
Recursively print inner exceptions by default

### ISSUE THREAD

**Issue by cmeeren** [haf/expecto#348]
I propose that inner exceptions are printed by default. I am running an integration test using Hopac, and this is the test results I see:

![image](https://user-images.githubusercontent.com/7766733/66207265-a77c0200-e6b2-11e9-815d-629497d252a7.png)

This message says nothing about what is wrong. The inner exceptions eventually say stuff along the lines of "server not reachable", which is helpful, but I can't see that.

Let me know if there's a simple config adjustment for this (I couldn't find any config docs and was unable and unwilling to reverse-engineer it.)

**Comment by haf** [comment]
Fixed with #349

**Comment by cmeeren** [comment]
Wonderful, thanks! 🎉

**Comment by cmeeren** [comment]
Would it be possible to release this on NuGet? 🙏

**Comment by haf** [comment]
Yes, of course. Sorry for the wait. https://www.nuget.org/packages/Expecto/8.13.0 is the newest release out now!

**Comment by cmeeren** [comment]
Thanks, but it doesn't seem to be fixed. I still get exactly the same result, just the "Exception raised by job" without any inner exceptions. (For good measure I deleted all bin/obj/.vs and restarted.)

**Comment by haf** [comment]
cc @MNie
